apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
type: Opaque
data:
  DB_PASSWORD: cGFzc3dvcmQ=  # 'password' base64 encoded
  API_KEY: ZXhhbXBsZWFwaWtleQ==  # 'exampleapikey' base64 encoded