apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: backend-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-rolebinding
subjects:
- kind: User
  name: backend-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: backend-role
  apiGroup: rbac.authorization.k8s.io