apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/ryanparsa/gitops.git"
    targetRevision: HEAD
    path: 'k8s/backend/prod' 
  destination:
    server: "https://kubernetes.default.svc"
    namespace: backend-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
